FROM node:14-slim

# Set the working to /app
WORKDIR /app

#Copy the package.json and package-lock.json files to the container
COPY package*.json ./

#Install any needed packages specified in package.json
RUN npm install

#Copy the rest of the application files to the container
COPY . .

#Install python and pip
RUN apt-get update && apt-get install -y python3-pip

#Install paho-mqtt library for python
RUN pip install paho-mqtt

#Expose the port on which app will run
EXPOSE 3000

CMD ["npm", "start"]
